version: '3'

services:

    # Service PHP
    php:
        build:
            context: .  # Contexte de construction
            dockerfile: Dockerfile  # Fichier Docker à utiliser
            target: preprod
        volumes:
            - .:/var/www/html  # Montage du code source

    # Service Nginx
    nginx:
        image: nginx:1.21.3
        ports:
            - "8002:80"  # Port exposé
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf  # Config Nginx
            - .:/var/www/html  # Montage du code source

    # Service MySQL
    db_preprod:
        image: mysql:5.7
        environment:
            MYSQL_DATABASE: ${PREPROD_MYSQL_DATABASE}
            MYSQL_USER: ${PREPROD_MYSQL_USER}
            MYSQL_PASSWORD: ${PREPROD_MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${PREPROD_MYSQL_ROOT_PASSWORD}
        volumes:
            - db_preprod_data:/var/lib/mysql
        
        

    # Service Composer
    composer:
        image: composer:2.1.9
        container_name: composer_service
        volumes:
            - .:/var/www/html  # Montage du code source
        working_dir: /var/www/html
        command: ["composer", "install"]  # Commande initiale


volumes: 
    db_preprod_data:
