version: '3'

services:

    # Service PHP
    php:
        build:
            context: .  # Contexte de construction
            dockerfile: Dockerfile  # Fichier Docker à utiliser
            target: prod
        volumes:
            - .:/var/www/html  # Montage du code source

    # Service Nginx
    nginx:
        image: nginx:latest
        ports:
            - "8001:80"  # Port exposé
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf  # Config Nginx
            - .:/var/www/html  # Montage du code source

    # Service MySQL
    db_prod:
        image: mysql:5.7
        environment:
            MYSQL_DATABASE: ${PROD_MYSQL_DATABASE}
            MYSQL_USER: ${PROD_MYSQL_USER}
            MYSQL_PASSWORD: ${PROD_MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${PROD_MYSQL_ROOT_PASSWORD}
        volumes:
            - db_prod_data:/var/lib/mysql

    # Service Composer
    composer:
        image: composer:latest
        container_name: composer_service
        volumes:
            - .:/var/www/html  # Montage du code source
        working_dir: /var/www/html
        command: ["composer", "install"]  # Commande initiale

volumes:
    db_prod_data: